title: Userge Docs
description: The complete documentation of Userge
show_downloads: false
theme: jekyll-theme-cayman
buttons:
      zip_url: https://github.com/UsergeTeam/Userge
      zip_title: Main Repo
      zip_hide: false
      tar_url: https://github.com/UsergeTeam/Userge-Plugins
      tar_title: Plugins Repo
      tar_hide: false
      github_hide: true
